CREATE TRIGGER [OnNewUserCreated]
	ON AspNetUsers
	FOR INSERT
	AS
	BEGIN
		SET NOCOUNT ON;

		INSERT INTO Carts DEFAULT VALUES;
		INSERT INTO UserCarts(CartId, UserId) VALUES(SCOPE_IDENTITY(), (
			SELECT I.Id
			FROM inserted I
		));
	END
