DELETE FROM [dbo].[CategorySubcategories]
GO

INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (2, 29)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (3, 37)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (3, 38)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (3, 39)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (4, 13)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (2, 28)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (13, 35)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (13, 36)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (5, 14)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (5, 15)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (5, 15)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (5, 16)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (5, 20)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (5, 21)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (6, 22)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (6, 23)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (7, 25)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (7, 26)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (6, 31)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (5, 40)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (8, 32)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (8, 33)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (8, 34)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (17, 9)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (17, 18)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (17, 19)
INSERT INTO [dbo].[CategorySubcategories] ([CategoryId], [SubcategoryId]) VALUES (9, 27)
