version: "3.7"

services:
        mssql:
            image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
            container_name: mssql
            restart: on-failure
            user: root
            deploy:
                resources:
                    limits:
                        cpus: "0.5"
                        memory: 1512M
            ports:
                - 1433:1433
            environment:
                - ACCEPT_EULA=Y
                - SA_PASSWORD=mYAwesomePassw0rd
            networks:
                - microsoftSQL
            volumes:
                - db-data:/var/opt/mssql/data

        postgres:
            image: postgres
            restart: on-failure
            ports:
                - 5432:5432
            environment:
                POSTGRES_PASSWORD: mYAwesomePassw0rd

        adminer:
            image: adminer
            restart: on-failure
            ports:
            - 8080:8080
        
        rabbitmq:
            image: rabbitmq:3-management
            container_name: rabbitmq
            deploy:
                resources:
                    limits:
                        cpus: "0.5"
                        memory: 512M
            restart: on-failure
            ports:
                - 5672:5672
                - 15672:15672
            networks:
                - microsoftSQL

        elasticsearch:
            image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
            container_name: elasticsearch
            deploy:
                resources:
                    limits:
                        cpus: "0.5"
                        memory: 512M
            environment:
                - discovery.type=single-node
            volumes:
                - esdata1:/usr/share/elasticsearch/data
            restart: on-failure
            ports:
                - 9200:9200
                - 9300:9300
            networks:
                - microsoftSQL
               
        logstash:
            image: docker.elastic.co/logstash/logstash:7.16.0
            environment:
                LS_JAVA_OPTS: "-Xmx256m -Xms256m"
            command: logstash -f /etc/logstash/logstash.conf
            deploy:
                resources:
                    limits:
                        cpus: "0.5"
                        memory: 512M
            volumes:
            - ./logstash/config/logstash.conf:/etc/logstash/logstash.conf
            - ./logstash/mssql-jdbc-9.4.1.jre8.jar:/usr/share/logstash/logstash-core/lib/jars/mssql-jdbc-9.4.1.jre8.jar
            ports:
                - '5001:5001'
            container_name: logstash
            restart: on-failure
            networks:
                - microsoftSQL
            links:
                - elasticsearch
            depends_on:
                - elasticsearch

        kibana:
            image: docker.elastic.co/kibana/kibana:7.16.0
            container_name: kibana
            deploy:
                resources:
                    limits:
                        cpus: "0.5"
            restart: on-failure
            ports:
                - 5601:5601
            environment:
                - ELASTICSEARCH_URL=http://elasticsearch:9200
            networks:
                - microsoftSQL
            links:
                - elasticsearch

networks:
        microsoftSQL:
            driver: bridge

volumes:
        db-data:
        esdata1:
            driver: local