CREATE TABLE [dbo].[Categories]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CategoryName] NVARCHAR(100) NOT NULL, 
    [Description] NVARCHAR(2000) NOT NULL,
    [ImageId] INT NULL,
    [CreatedAt] DATETIME2 DEFAULT GETUTCDATE(),
    [UpdatedAt] DATETIME2 DEFAULT GETUTCDATE(),
    CONSTRAINT [FK_Categories_Images] FOREIGN KEY ([ImageId]) REFERENCES Images(Id) ON DELETE SET NULL
)
