CREATE TABLE [dbo].[TvSetDetails]
(
	[ProductId] INT NOT NULL,
	[Warranty] TINYINT NOT NULL DEFAULT 0,
	[MadeIn] NVARCHAR(100) NOT NULL,
	[Type] NVARCHAR(100) NOT NULL,
	[Model] NVARCHAR(200) NOT NULL,
	[Voltage] NVARCHAR(100) NOT NULL,
	[YearOfManufacture] INT NOT NULL,
	[ScreenSize] REAL NOT NULL,
	[ScreenResolution] VARCHAR(100) NOT NULL,
	[ScreenFormat] VARCHAR(50) NOT NULL,
	[RefreshRate] SMALLINT NULL,
	[MatrixType] VARCHAR(20) NOT NULL,
	[SmartTvOs] VARCHAR(50) NULL,
	[Wifi] BIT NOT NULL,
	[SoundPower] TINYINT NULL,
	[Subwoofer] BIT NOT NULL,
	[ExternalStoragePlay] BIT NOT NULL,
	[ExternalStorageInterface] VARCHAR(50) NULL,
	[VideoCodecs] VARCHAR(200) NULL,
	[HdmiPorts] TINYINT NULL,
	[HdmiVersion] FLOAT NULL,
	[HeadphoneOut] BIT NOT NULL,
	[Height] SMALLINT NOT NULL,
	[Width] SMALLINT NOT NULL,
	[Depth] SMALLINT NOT NULL,
	[Weight] REAL NOT NULL,
	CONSTRAINT [FK_TvSetDetails_Products] FOREIGN KEY ([ProductId]) REFERENCES Products(Id),
	CONSTRAINT [CHK_YearOfManufacture] CHECK ([YearOfManufacture] >= 2000 AND [YearOfManufacture] <= year(GETUTCDATE()))
)
